# Deploy
k8s_yaml(['./catalog-service.yaml','./config-service.yaml', './order-service.yaml'])

# Manage
k8s_resource('catalog-service', port_forwards=['9001'])
k8s_resource('order-service', port_forwards=['9002'])